// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TTu_5h3EP5ytRiUgGzqSVLPanM9dg3M',
    appId: '1:732889943106:web:de144f7e61bfc85142b1db',
    messagingSenderId: '732889943106',
    projectId: 'realtime-database-cbd8c',
    authDomain: 'realtime-database-cbd8c.firebaseapp.com',
    storageBucket: 'realtime-database-cbd8c.appspot.com',
    measurementId: 'G-YG8Y86YYMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7p15RoYlLYHVqFb_ZGRrn7QAsqDdFCso',
    appId: '1:732889943106:android:5e547f6fb7a0941242b1db',
    messagingSenderId: '732889943106',
    projectId: 'realtime-database-cbd8c',
    storageBucket: 'realtime-database-cbd8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOpPKHGW2WQ75OMd_ZA9Jqdba5cK4B5A',
    appId: '1:732889943106:ios:232effd5c02fb27042b1db',
    messagingSenderId: '732889943106',
    projectId: 'realtime-database-cbd8c',
    storageBucket: 'realtime-database-cbd8c.appspot.com',
    iosBundleId: 'com.example.realtimeDatabase',
  );
}
